## -*- encoding: utf-8 -*-
## This file (digInLimitsOfTheFormZeroOverZero.sagetex.sage) was *autogenerated* from digInLimitsOfTheFormZeroOverZero.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('digInLimitsOfTheFormZeroOverZero', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
